import type {
  TripRequest,
  Principal,
  PrincipalDetail,
  VerificationItem,
} from "@/types";

export const tripRequest: TripRequest = {
  id: "VYX-2026-0847",
  status: "sourcing_quotes",
  statusLabel: "Sourcing quotes",
  client: "Westbourne Family Office",
  clientTier: "VIP Tier 1",
  booker: "Amelia Hartford",
  bookerRole: "Principal EA",
  createdAgo: "12 min ago",
  fromCode: "DUBAI",
  fromIcao: "OMDW",
  toCode: "LONDON",
  toIcao: "EGGW",
  dateLabel: "Sat 14 March 2026 · Depart 09:30 GST",
  pax: "6 adults + 2 children",
  aircraftPref: "Heavy / ultra-long-range preferred",
  catering: "Halal catering · child car seats at LTN",
  groundTransport: "Ground transport to Mayfair",
  budgetMin: 85000,
  budgetMax: 115000,
  quotes: [
    {
      id: "q1",
      operator: "Sovereign Jet Partners",
      aocId: "GCAA-OPS-3471",
      jurisdiction: "UAE",
      verified: true,
      aircraft: "Bombardier Global 7500",
      tail: "A6-SJP",
      yearBuild: 2023,
      hoursSinceNew: 1247,
      insurance: "$500M hull / $1B liability",
      insurer: "Allianz",
      insuranceExpiry: "Aug 2026",
      safety: "ARG/US Platinum · IS-BAO Stage 3",
      price: 94500,
      safNote: "includes $4,200 SAF at 30% blend",
      trustScore: 98,
      respondedAgo: "Responded 1m 12s ago",
      recommended: true,
      status: "received",
    },
    {
      id: "q2",
      operator: "Crescent Aviation",
      aocId: "GCAA-OPS-1129",
      jurisdiction: "UAE",
      verified: true,
      aircraft: "Gulfstream G650ER",
      tail: "A6-CRA",
      yearBuild: 2021,
      hoursSinceNew: 2890,
      insurance: "$350M / $750M",
      insurer: "AIG",
      insuranceExpiry: "Mar 2027",
      safety: "ARG/US Gold · Wyvern Wingman",
      price: 89200,
      safNote: "SAF available +$3,800",
      trustScore: 91,
      respondedAgo: "Responded 6m ago",
      status: "received",
    },
    {
      id: "q3",
      operator: "Meridian Charter Group",
      aocId: "UK CAA AOC 2247",
      jurisdiction: "UK",
      verified: true,
      aircraft: "Dassault Falcon 8X",
      tail: "G-MCG88",
      yearBuild: 2022,
      hoursSinceNew: 1654,
      insurance: "$300M hull",
      insurer: "AXA",
      insuranceExpiry: "Nov 2026",
      safety: "ARG/US Gold",
      price: 78400,
      safNote: "SAF not offered",
      trustScore: 87,
      trustNote: "lower due to no SAF + smaller cabin",
      respondedAgo: "Responded 8m ago",
      status: "received",
    },
    {
      id: "q4",
      operator: "VistaJet",
      aocId: "—",
      jurisdiction: "—",
      verified: false,
      aircraft: "—",
      tail: "—",
      yearBuild: 0,
      hoursSinceNew: 0,
      insurance: "—",
      insurer: "—",
      insuranceExpiry: "—",
      safety: "—",
      price: 0,
      safNote: "",
      trustScore: 0,
      respondedAgo: "",
      status: "pending",
      pendingNote: "quote arriving... typical response 2–4 min",
    },
  ],
  trust: {
    clientRisk: "Low — verified entity, 47 prior bookings on Voyex",
    escrow: "$115,000 funded · ref VX-7-291",
    compliance: "KYC current · sanctions clear · all pax cleared",
    recovery: "3 backup aircraft within 4hrs of DWC if disruption",
  },
  activity: [
    { time: "12:04", text: "Quote requested" },
    { time: "12:05", text: "Sovereign responded" },
    { time: "12:06", text: "Crescent responded" },
    { time: "12:08", text: "Meridian responded" },
    { time: "12:09", text: "VistaJet acknowledged" },
  ],
};

export const principals: Principal[] = [
  {
    id: "p1",
    initials: "KR",
    name: "HRH Sheikh Khalid Al-Rashid",
    role: "Chairman, Al-Rashid Holdings",
    ytdHours: 47,
    status: "green",
  },
  {
    id: "p2",
    initials: "JP",
    name: "Lord James Pemberton",
    role: "Trustee, Pemberton Trust",
    ytdHours: 89,
    status: "green",
  },
  {
    id: "p3",
    initials: "MS",
    name: "Maria Sokolova",
    role: "CEO, Nova Capital",
    ytdHours: 124,
    status: "amber",
  },
  {
    id: "p4",
    initials: "AF",
    name: "Dr. Ahmed Farouk",
    role: "Family Principal",
    ytdHours: 31,
    status: "green",
  },
  {
    id: "p5",
    initials: "CW",
    name: "Catherine Westbourne",
    role: "Principal",
    ytdHours: 156,
    status: "green",
  },
];

export const catherine: PrincipalDetail = {
  id: "p5",
  initials: "CW",
  name: "Catherine Westbourne",
  role: "Principal",
  ytdHours: 156,
  status: "green",
  tier: "Tier 1 VIP",
  office: "Westbourne Family Office",
  preferences: [
    { label: "Aircraft preference", value: "Ultra-long-range only" },
    { label: "Cabin temperature", value: "19°C" },
    { label: "Seat", value: "Forward-facing, left side" },
    { label: "Meal", value: "Pescatarian, no shellfish" },
    { label: "Beverage", value: "Dom Pérignon 2013, Diet Coke (Mexican)" },
    { label: "Allergies", value: "Penicillin, tree nuts" },
  ],
  approval: [
    { range: "Under $50,000", rule: "Auto-approved by EA" },
    {
      range: "$50,000 – $150,000",
      rule: "Requires CFO sign-off (Marcus Webb)",
    },
    { range: "Above $150,000", rule: "Requires Principal + CFO" },
  ],
  companions: [
    "2 children registered (passports in vault, expiry tracked)",
    "Regular companion: Mr. David Westbourne (spouse)",
  ],
  linkedEntities: [
    { name: "Westbourne Family Office", note: "primary billing" },
    {
      name: "Westbourne Trust III",
      note: "alt billing — personal/non-business travel",
    },
  ],
  recentTrips: [
    {
      date: "08 Mar 2026",
      route: "LCY → NCE",
      aircraft: "Global 6000",
      price: 42800,
    },
    {
      date: "24 Feb 2026",
      route: "LTN → DXB",
      aircraft: "Global 7500",
      price: 96200,
    },
    {
      date: "11 Feb 2026",
      route: "LTN → JFK",
      aircraft: "Gulfstream G650",
      price: 134500,
    },
    {
      date: "02 Feb 2026",
      route: "GVA → LTN",
      aircraft: "Citation Longitude",
      price: 28900,
    },
    {
      date: "18 Jan 2026",
      route: "LTN → MXP",
      aircraft: "Falcon 7X",
      price: 24300,
    },
  ],
};

export const verificationChecklist: VerificationItem[] = [
  {
    status: "ok",
    label: "Operator AOC verified",
    detail: "Sovereign Jet Partners, GCAA-OPS-3471",
  },
  {
    status: "ok",
    label: "Aircraft airworthiness current",
    detail: "last check 8 days ago via CAMP",
  },
  {
    status: "ok",
    label: "Crew currency confirmed",
    detail: "Capt. Michael Hadid, 4,200 hrs on type",
  },
  {
    status: "ok",
    label: "Insurance certificate valid",
    detail: "Allianz, expires Aug 2026",
  },
  { status: "ok", label: "Passenger KYC complete", detail: "6 of 6" },
  {
    status: "ok",
    label: "Route permits clear",
    detail: "UAE airspace, EU airspace",
  },
  {
    status: "pending",
    label: "FBO slot confirming",
    detail: "Jetex DWC → Signature LTN — 3 min remaining",
  },
];

export function formatUsd(n: number) {
  return `$${n.toLocaleString("en-US")}`;
}
